# Load Valid Data & Auto Send failure records to Client


CREATE OR REPLACE TABLE CUSTOMER
(C_CUSTKEY	int
,C_NAME	varchar
,C_ADDRESS	varchar
,C_NATIONKEY	int
,C_PHONE	varchar
,C_ACCTBAL	varchar
,C_MKTSEGMENT	varchar
,C_COMMENT	varchar
,N_NAME	varchar
,Load_date Date);

create or Replace file format CSVTYPE
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
FIELD_OPTIONALLY_ENCLOSED_BY = " "
DATE_FORMAT = 'DD-MM-YYYY'
COMPRESSION = NONE;

CREATE OR REPLACE STORAGE INTEGRATION AWS_INT
TYPE = EXTERNAL_STAGE
ENABLED_TRUE
STROAGE_PROVIDER = 'S3'
STORAGE_AWS_ROLE_ARN = 'YOUR_ROLE_ARN'
STORAGE_ALLOWED_LOCATION = ('YOUR BUCKET URL');

--SORUCE STAGE
CREATE OR REPLACE STAGE AWS_STAGE
STORAGE_INTEGRATION = AWS_INT
URL = 'YOUR BUCKET URL'
FILE_FORMAT = 'CSVTYPE';

LIST @AWS_STAGE

--TARGET STAGE
CREATE OR REPLACE STAGE AWS_TARGET_STAGE
STORAGE_INTEGRATION = AWS_INT
URL = 'YOUR BUCKET URL'
FILE_FORMAT = 'CSVTYPE;

--COPY ALL CORRECT RECORD IN TARGET TABLE
COPY INTO CUSTOMER FROM @AWS_STAGE 
ON_ERROR = CONTINUE;

SELECT * FROM CUSTOMER;

SELECT * FROM TABLE(VALIDATE(CUSTOMER, JOB_ID => '_LAST'));

--COPY FAULTY RECORDS IN NEW TABLE
CREATE OR REPLACE TABLE FAULTY_RECORDS AS 
SELECT FILE, CATEGORY, ERROR, REJECTED_RECORD FROM TABLE(VALIDATE(CUSTOMER, JOB_ID => '_LAST'));

SELECT * FROM FAULTY_RECORDS;

-- TRANSFER FAILURE RECORDS FROM SNOWFLAKE TO S3 FOR CUSTOMER
COPY INTO @AWS_TARGET_STAGE/faultyrecords.csv FROM FAULTY_RECORDS
SINGLE = TRUE;

CREATE OR REPLACE PROCEDURE FAULTY_RECORDS_EXPORT(
 TABLE_NAME STRING,
 SOURCE_STAGE STRING,
 TARGET_STAGE STRING)
RETURN STRING
LANGUAGE SQL
AS 
$$
BEGIN
  -- Step 1: Load valid records into the target table
    LET COPY_SQL := '
        COPY INTO ' || TABLE_NAME || '
        FROM @' || SOURCE_STAGE || '
        ON_ERROR = CONTINUE;';
    EXECUTE IMMEDIATE :COPY_SQL;

    -- Step 2: Save failed records into a new table
    LET VALIDATE_SQL := '
        CREATE OR REPLACE TABLE FAULTY_RECORDS AS
        SELECT   FILE,CATEGORY,ERROR,REJECTED_RECORD
        FROM TABLE(
            VALIDATE(' || TABLE_NAME || ', JOB_ID => ''_last''));';
    EXECUTE IMMEDIATE :VALIDATE_SQL;

    -- Step 3: Export failed records to S3 stage
    LET EXPORT_SQL := '
        COPY INTO @' || TARGET_STAGE || '/faultyrecords.csv
        FROM FAULTY_RECORDS
        SINGLE = TRUE
        OVERWRITE = TRUE;';
    EXECUTE IMMEDIATE :EXPORT_SQL;

    RETURN 'Load and export completed successfully.';
END;
$$;

CALL FAULTY_RECORDS_EXPORT('CUSTOMER','AWS_STAGE','AWS_TARGET_STAGE');


Select * from customer;

Select * from faulty_records;