# Automate Data Loads from S3 Dynamic Day-Wise Folders to Snowflake

CREATE OR REPLACE TABLE CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER WHERE 1 = 2;

CREATE OR REPLACE STORAGE INTEGRATION AWS_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STROAGE_ALLOWED_LOCATION = ('YOUR URL')
STORAGE_AWS_ROLE_ARN = 'YOUR ROLE ARN';

DESC INTEGRATION AWS_INT;

CREATE OR REPLACE STAGE CUST_DYNAMIC_STAGE
STORAGE_INTEGRATION = AWS_INT
URL = 'YOUR URL'
FILE_FORMAT = 'YOUR FILE FORMAT'

LIST @CUST_DYNAMIC_STAGE;

CREATE OR REPLACE PROCEDURE DYNAMIC_LOAD()
RETURN STRING
LANGUAGE SQL
AS
$$
BEGIN
   LET var_year:= TO_CHAR(CURRENT_DATE(), 'YYYY');
   LET var_month := TO_CHAR(CAST(CURRENT_DATE() AS DATE), 'MM');
   LET var_day := TO_CHAR(CAST(CURRENT_DATE() AS DATE), 'DD');

   LET var_full_s3_path := '/' || var_year || '/' || var_month || '/' || var_day || '/' ;

   LET  var_copy_statement := 'COPY INTO CUSTOMER' || 'FROM @CUST_DYNAMIC_STAGE' || var_full_s3_path || ' ' ||';

   EXECUTE IMMEDIATE :var_copy_statement;

   RETURN 'Executed SQL: ' || var_copy_statement;

END;
$$

CALL DYNAMIC_LOAD();

select * from customer;

